# fly.toml app configuration file generated for restless-mountain-5540 on 2023-10-15T16:09:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-mountain-5540"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
